"""empty message

Revision ID: 9e108eab0ae3
Revises: 6323cee85327
Create Date: 2024-10-20 22:07:15.041716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e108eab0ae3'
down_revision = '6323cee85327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedy', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_email', ['email'], unique=False)
        batch_op.create_index('idx_username', ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_username')
        batch_op.drop_index('idx_email')

    with op.batch_alter_table('remedy', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
